In [24]:
#3-a:create a white image using numpy

#import required libraries
from PIL import Image
import numpy as np

#create a white image
a=np.full((512,256,3),255,dtype = np.uint8)
Image=Image.fromarray(a,"RGB")
Image.save("white.png","PNG")
Image.show()

In [17]:
#3-b: Convert images to NumPy array

# Converting an image into NumPy Array

# Import the necessary libraries
from PIL import Image
from numpy import asarray

# load the image and convert into numpy array
img = Image.open('Sample.png')

# asarray() class is used to convert PIL images into NumPy arrays
numpydata = asarray(img)

# <class 'numpy.ndarray'>
print(type(numpydata))

# shape
print(numpydata.shape)


<class 'numpy.ndarray'>
(200, 400, 3)


In [8]:
# 3-b2: Convert a NumPy array to an image

from PIL import Image
import numpy as np
w,h=250,250
t=(h,w,3)
A=np.zeros(t,dtype=np.uint8)
for i in range(h):
    for j in range(w):
        A[i,j]=[i%256,j%256,(i+j)%256]
i=Image.fromarray(A,"RGB")
i.show()

In [1]:
#3-c: Perform Sorting, Searching and Counting using Numpy methods.

# importing libraries
import numpy as np
 
# sort along the first axis
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)        
print ("Along first axis : \n", arr1)        
 
# sort along the last axis
a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1)        
print ("\nAlong first axis : \n", arr2)
 
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = None)        
print ("\nAlong none axis : \n", arr1)


#Searching
import numpy as np
array = np.arange(12).reshape(3, 4)
print("Input ARRAY : \n", array)
 
# No axis mentioned, so works on entire array
print("\nMax element : ", np.argmax(array))
 
# returning Indices of the max element as per the indices
print(("\nIndices of Max element : ", np.argmax(array, axis=0)))
print(("\nIndices of Max element : ", np.argmax(array, axis=1)))


#Counting
import numpy as np
  
# Counting a number of non-zero values
a = np.count_nonzero([[0,1,7,0,0],[3,0,0,2,19]])
b = np.count_nonzero(([[0,1,7,0,0],[3,0,0,0,19]]))
 
print("Number of nonzero values is :",a)
print("Number of nonzero values is :",b)

Along first axis : 
 [[10  1]
 [12 15]]

Along first axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]
Input ARRAY : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Max element :  11
('\nIndices of Max element : ', array([2, 2, 2, 2], dtype=int64))
('\nIndices of Max element : ', array([3, 3, 3], dtype=int64))
Number of nonzero values is : 5
Number of nonzero values is : 4


In [9]:
# 3-d: Write a program to demonstrate the use of the reshape() method.

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

#Unknown Dimension
newarr = arr.reshape(2, 2, -1)
print("\n")
print(newarr)

#Flattening the arrays
newarr = arr.reshape(-1)
print("\n")
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [1]:
#water jug problem
from collections import defaultdict
jug1,jug2,aim=4,3,2
visited=defaultdict(lambda:False)
def waterjugsolver(amt1,amt2):
    if(amt1==aim and amt2==0)or(amt2==aim and amt1==0):
        print(amt1,amt2)
        return True
    if visited[(amt1,amt2)]==False:
        print(amt1,amt2)
        visited[(amt1,amt2)]=True
        return(waterjugsolver(0,amt2)or waterjugsolver(amt1,0) or
               waterjugsolver(jug1,amt2) or
               waterjugsolver(amt1,jug2)or
               waterjugsolver(amt1+min(amt2,(jug1-amt1)),amt2-min(amt2,(jug1-amt1)))or
               waterjugsolver(amt1-min(amt1,(jug2-amt2)),
                              amt2+min(amt1,(jug2-amt2))))
    else:
        return False
print("steps")
waterjugsolver(0,0)
    

steps
0 0
4 0
4 3
0 3
3 0
3 3
4 2
0 2


True

In [ ]:
import collections from defaultdict:
jug1,jug2,aim=4,3,2
visited=defaultdict(lambda:False)
def waterjugsolver(amt1,amt2):
    if((amt1==aim and amt2==0)or(amt2==aim and amt1==0):
        print(amt1,amt2)
        return true
    if vi

