In [2]:
import numpy as np
list1=[1,2,3]
print(type(list1))
print(list1)



<class 'list'>
[1, 2, 3]


In [9]:
import numpy as np
list1=[1,2,3]
print(type(list1))
print(list1)
#conversion
array1= np.array(list1)
print(type(array1))
print(array1)
tuple1=((1,2,3))
print(type(tuple1))
print(tuple1)
#conversion
array2=np.array(tuple1)
print(array2)
array3=np.array([tuple1,list1,array2])
print(type(array3))
print(array3)


<class 'list'>
[1, 2, 3]
<class 'numpy.ndarray'>
[1 2 3]
<class 'tuple'>
(1, 2, 3)
[1 2 3]
<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [11]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a[...,1])
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,0,1]])
import numpy as np
a=np.array([10,40,80,50,100])
print(a[a>50])
import numpy as np
b=np.array([[5,5],[4,5],[16,4]])
sumrow=b.sum(-1)
print(b[sumrow%10==0])

[[ 2  5]
 [ 8 11]]
[1 3 6]
[ 80 100]
[[ 5  5]
 [16  4]]


In [19]:
import numpy 
arr=numpy.array([1,5,4,8,3,7])
max_element=numpy.max(arr)
min_element=numpy.min(arr)
print('maximum elements in the array is:',max_element)
print('minimum elements in the array is:',min_element)
list=[10,20,30,40,50]
new_list=[]
j=0
for j in range(0,len(list)):
    j+=list[j]
    new_list.append(j)
print(new_list)

maximum elements in the array is: 8
minimum elements in the array is: 1
[10, 21, 32, 43, 54]


In [20]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("dimension of the given ndarray=",a.ndim)
print("shape of the given ndarray=",a.shape)
print("datatype of given ndarray=",a.dtype)
print("size of the given ndarray=",a.size)
print("size of each element in ndarray=",a.itemsize)


dimension of the given ndarray= 3
shape of the given ndarray= (2, 2, 3)
datatype of given ndarray= int32
size of the given ndarray= 12
size of each element in ndarray= 4
