In [1]:
import numpy as np 
my_matrix=np.array([[1,2,1],[3,4,7],[3,6,3]])
print("matrix")
for row in my_matrix:
    print(row)
rank=np.linalg.matrix_rank(my_matrix)
print("rank of the given matrix is :",rank)
#determent
import numpy as np
a=np.array([[1,2],[3,4]])
print("original array")
print(a)
result=np.linalg.det(a)
print("determinent of the said array:")
print(result)
import numpy as np
mx=np.array([[1,1,1],[0,1,2],[1,5,3]])
print(mx.trace())

matrix
[1 2 1]
[3 4 7]
[3 6 3]
rank of the given matrix is : 2
original array
[[1 2]
 [3 4]]
determinent of the said array:
-2.0000000000000004
5


In [2]:
import numpy as np
m=np.array([[1,2],[2,3]])
print("printing the orignal square array:\n",m)
w,v=np.linalg.eig(m)
print("printing the eigen values of the given square array:\n",w)
print("printing the right eigen vectors of the given square array:\n",v)

printing the orignal square array:
 [[1 2]
 [2 3]]
printing the eigen values of the given square array:
 [-0.23606798  4.23606798]
printing the right eigen vectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [3]:
import numpy as np
a=np.array([2,6])
b=np.array([3,10])
print("vectors:")
print("a=",a)
print("\nb=",b)
print("\n inner product of vectors a and b=")
print(np.inner(a,b))
print("---------------------------")
print("\n outer product of vectors a and b= ")
print(np.outer(a,b))
print("---------------------------")
print(" cross product of vectors a and b=")
print(np.cross(a,b))

vectors:
a= [2 6]

b= [ 3 10]

 inner product of vectors a and b=
66
---------------------------

 outer product of vectors a and b= 
[[ 6 20]
 [18 60]]
---------------------------
 cross product of vectors a and b=
2


In [1]:
#2-d: Write a python program to solve a linear matrix equation, or system of linear scalar equations.

import numpy as np

# Creating two 2D numpy arrays using the array() method

# Consider the system of equations x0 + 2 * x1 = 1 and 3 * x0 + 5 * x1 = 2
arr1 = np.array([[1, 2], [3, 5]])
arr2 = np.array([1, 2])

# Display the arrays
print("Array1...\n",arr1)
print("\nArray2...\n",arr2)

# Check the Dimensions of both the arrays
print("\nDimensions of Array1...\n",arr1.ndim)
print("\nDimensions of Array2...\n",arr2.ndim)

# Check the Shape of both the arrays
print("\nShape of Array1...\n",arr1.shape)
print("\nShape of Array2...\n",arr2.shape)

# To solve a linear matrix equation, use the numpy.linalg.solve() method in Python.
print("\nResult...\n",np.linalg.solve(arr1, arr2))

Array1...
 [[1 2]
 [3 5]]

Array2...
 [1 2]

Dimensions of Array1...
 2

Dimensions of Array2...
 1

Shape of Array1...
 (2, 2)

Shape of Array2...
 (2,)

Result...
 [-1.  1.]
